mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = "polls"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from __future__ import unicode_literals

import datetime
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.db import models




# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}"/>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i|Scope+One" rel="stylesheet"/>
  <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}"/>
</head>

<body>
  <div class="container">
    <div class="row header">
      <h1>{{ question.question_text }}</h1>
    </div>

    <hr>
    <br>

    <div class="row choices">
      <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
          <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
      {% endfor %}
      <br>
      <br>
      <div class="row error">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      </div>
      <br>
      <input class="vote-button" type="submit" value="Vote"/>
      </form>
    </div>

  </div>

</body>

</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}"/>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i|Scope+One" rel="stylesheet"/>
  <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}"/>
</head>

<body>
  <div class="container">
    <div class="row header">
      <h1>Current Polls</h1>
    </div>

    <hr>
    <br>

    <div class="row list">
      {% if latest_question_list %}
          <ul>
          {% for question in latest_question_list %}
              <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
          {% endfor %}
          </ul>
      {% else %}
          <p>No polls are available.</p>
      {% endif %}
    </div>

  </div>
</body>

</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}"/>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i|Scope+One" rel="stylesheet"/>
  <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}"/>
</head>

<body>
  <div class="container">
    <div class="row header">
      <h1>{{ question.question_text }} -- Results</h1>
    </div>

    <hr>
    <br>

    <div class="row">
      <ul>
      {% for choice in question.choice_set.all %}
          <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
      {% endfor %}
      </ul>
    </div>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
  </div>
</body>

</html>